pub mod auth_routes;
pub mod issue_routes;
pub mod merchant_routes;
pub mod payment_routes;
pub mod product_routes;
pub mod transaction_routes;
pub mod user_routes;
pub mod wallet_routes;
pub mod workspace_routes;
// pub mod auth_routes;
// pub mod barbershop_routes;
// pub mod client_routes;
// pub mod product_routes;
// pub mod subscription_routes;
